<?php
/**
 * @file
 * Kaltura Chunked Uploader
 */

/**
 * Implements hook_menu().
 */
function kaltura_chunked_uploader_menu()
{
  $items = array();

  $items['kaltura/%ctools_js/chunked-upload/%'] = array(
    'title' => 'Add Kaltura Media',
    'type' => MENU_CALLBACK,
    'page callback' => 'kaltura_chunked_uploader_uploader',
    'page arguments' => array(1, 3),
    'access arguments' => array('access kaltura widgets'),
    'file' => 'includes/kaltura_chunked_uploader.uploader.inc',
  );

  $items['kaltura-chunked-uploader/ajax/add-media/%'] = array(
    'title' => 'Add Kaltura media from upload token',
    'type' => MENU_CALLBACK,
    'page callback' => 'kaltura_chunked_uploader_ajax_add_media',
    'page arguments' => array(3, 4),
    'access arguments' => array('access kaltura widgets'),
    'file' => 'includes/kaltura_chunked_uploader.uploader.inc',
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function kaltura_chunked_uploader_library()
{
  $libraries = array();

  $modulePath = drupal_get_path('module', 'kaltura_chunked_uploader');

  $libraries['chunked-file-upload-jquery'] = array(
    'title' => 'Kaltura Chunked File Upload using jQuery',
    'website' => 'https://github.com/kaltura/chunked-file-upload-jquery',
    'version' => '5.4.0',
    'js' => array_reduce(array(
      'jquery-1.12.4.min',
      'jquery-no-conflict',
      'jquery.ui.widget',
      'jquery.iframe-transport',
      'webtoolkit.md5',
      'jquery.fileupload',
      'jquery.fileupload-process',
      'jquery.fileupload-validate',
      'jquery.fileupload-kaltura',
      'jquery.fileupload-kaltura-base',
      'jquery.fileupload-drupal-7x',
    ), function (&$carry, $fileName) use ($modulePath) {
      $path = $modulePath . '/js/' . $fileName . '.js';
      $carry[$path] = array();
      return $carry;
    }, array()),
    'css' => array_reduce(array(
      'jquery.fileupload-ui-drupal',
    ), function (&$carry, $fileName) use ($modulePath) {
      $path = $modulePath . '/css/' . $fileName . '.css';
      $carry[$path] = array();
      return $carry;
    }, array()),
  );

  return $libraries;
}

/**
 * Implements hook_theme().
 */
function kaltura_chunked_uploader_theme($existing, $type, $theme, $path)
{
  return array(
    'kaltura_chunked_uploader_uploader' => array(
      'render element' => 'form',
      'template' => 'kaltura_chunked_uploader_uploader',
      'path' => $path . '/templates',
    ),
  );
}
